package com.n00b5.simplist.api.ebay.enums;

/**
 * Project: Simplist
 *
 * @author d4k1d23
 * @date 1/5/17
 */
public enum PackageTypeEnum {
    BULKY_GOODS, CARAVAN, CARS, EUROPALLET, EXPANDABLE_TOUGH_BAGS, EXTRA_LARGE_PACK,
    FURNITURE, INDUSTRY_VEHICLES, LARGE_CANADA_POST_BUBBLE_MAILER,
    LARGE_CANADA_POSTBOX, LARGE_ENVELOPE, LETTER, MAILING_BOX,
    MEDIUM_CANADA_POST_BOX, MEDIUM_CANADA_POST_BUBBLE_MAILER, MOTORBIKES,
    ONE_WAY_PALLET, PACKAGE_THICK_ENVELOPE, PADDED_BAGS, PARCEL_OR_PADDED_ENVELOPE,
    ROLL, SMALL_CANADA_POST_BOX, MALL_CANADA_POST_BUBBLE_MAILER, TOUGH_BAGS,
    UPS_LETTER, USPS_FLAT_RATE_ENVELOPE, USPS_LARGE_PACK,
    VERY_LARGE_PACK, WINE_PAK
}
